### ISSUE TITLE
MODE_LIVE not working

### ISSUE THREAD

**Issue by Shadow00Caster** [afosto/yaac#3] opened 2020-03-18 01:02 UTC
First off thanks for making this, it's really useful and not bloated like many of the other clients out there.

So I have been successful with the MODE_STAGING and the cert is being generated properly, however when I try to use MODE_LIVE, `$client->isReady($order)` always reports false, even after a do while false to wait for it to be ready with a usleep and total allowing a minute for processing (note that MODE_STAGING is almost instant).

I am using `$ok = $client->validate($authorization->getHttpChallenge(), 15)`.  I'm not sure if I need to allow for longer processing especially with LE now validating domains from multiple locations or if there is something else going on.  I do see the PEM for the LE account being created (test creation both with MODE_STAGING and MODE_LIVE -- same PEM which makes sense) so I know at least that part is working.

**Comment by bakkerpeter** [comment] 2020-03-18 11:07
Thanks for reporting, I'll look into this today.

**Comment by bakkerpeter** [comment] 2020-03-18 18:34
Thanks for submitting the issue. The issue is fixed with https://github.com/afosto/yaac/pull/4
I will make a new release, although it has a breaking change, therefore I will bump to 2.x

**Comment by bakkerpeter** [comment] 2020-03-19 09:09
Feel free to re-open if you still experience difficulties. Otherwise I would like to know if it's all good now :) Thanks

**Comment by Shadow00Caster** [comment] 2020-03-19 17:11
After adjusting some things on my end, everything is working great and this is being used as part of a larger platform and has significantly improved existing processes.

**Comment by bakkerpeter** [comment] 2020-03-19 19:08
Good to know. In order to keep a grasp of how this package is beeing used I would like to get your platform listed at https://github.com/afosto/yaac#who-is-using-it
Care to submit a PR to enlist it? Thanks!

**Comment by Shadow00Caster** [comment] 2020-03-19 19:17
I would love to, however this is an internal tool that is not public, I may adjust some things and put it on my GH for public consumption as nothing created or used is proprietary, it's just currently coupled up within a larger tool.

**Closed** 2020-04-29 05:54 UTC
Labels: bug
